set_property SRC_FILE_INFO {cfile:C:/Users/sebasala/Desktop/Work/UART_test/UART_TEST1/UART_TEST1/UART_TEST1.srcs/constrs_1/new/Constraints.xdc rfile:../../../UART_TEST1.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N15 [get_ports uart_rtl_rxd]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports uart_rtl_txd]
